librosonline/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('vistaprevia.urls')),
   #path('accounts/', include('registration.backends.default.urls')),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('usuario/', include('usuario.urls')),  
]  +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

tienda/urls.py
from django.urls import path
from tienda import views
from tienda import views_agregar
from tienda.views import VerImagenes
from tienda.views import EjemploLocalSotage

urlpatterns = [
    path('cargar/', views.cargar_imagen, name="cargar"),
    path('<int:producto_id>/ver/', views.ver_imagen, name="ver"),  
    path('verimagenes/', VerImagenes.as_view(), name="verimagenes"),
    path('ejemplo_localstorage/', EjemploLocalSotage.as_view(), name="ejemplo_localstorage"),
    path("agregar/", views_agregar.agregar, name="agregar"),
]

productos/models.py
from django.db import models
from django.utils.html import format_html


class Categoria(models.Model):
    nombre = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)

    def __str__(self):
        return '%s' % self.nombre


class Producto(models.Model):
    
    Borrador = 'Borrador'
    Publicado = 'Publicado'
    Retirado = 'Retirado'
    APROBACION_PRODUCTO = (
        (Borrador, 'Borrador'),
        (Publicado, 'Publicado'),
        (Retirado, 'Retirado'),    
    )
    estado = models.CharField(max_length=10, choices=APROBACION_PRODUCTO, default='Borrador')
    
    producto = models.CharField(max_length=200)
    fecha_publicacion = models.DateTimeField('Fecha de publicación')
    imagen = models.ImageField(upload_to="producto/%Y/%m/%d", blank=True, null=True)
    categoria = models.ForeignKey(
        Categoria, blank=False, null=True, on_delete=models.CASCADE
        )
    
    stock = models.IntegerField(default=0)
    descripcion = models.TextField(  default="")
    precio = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    descuento = models.IntegerField(default=0)


    def tipo_de_producto(self):
        if self.estado == "Retirado":
            return format_html(
                '<span style="color: #f00;">{}</span>',
                self.estado,
            )
        elif self.estado == "Borrador":
            return format_html(
                '<span style="background-color: #f0f; padding:7px;">{}</span>',
                self.estado,
            )
        elif self.estado == "Publicado":
            return format_html(
                '<span style="color: #099;">{}</span>',
                self.estado,
            )

    def __str__(self, ):
        return self.producto + "---" + str(self.fecha_publicacion)

tienda/models.py
from django.db import models

usuario/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
import time

class Datosusuario(models.Model):
    usuario = models.OneToOneField(User, blank=False, null=True, on_delete=models.CASCADE, related_name="perfil")
    imagen = models.ImageField(upload_to="producto/%Y/%m/%d", default='defecto/defecto.png', blank=True, null=True)
    nombre               =models.CharField(max_length=50)
    apellido             =models.CharField(max_length=50)
    fecha_nacimiento     =models.CharField(max_length=30, blank=True)
    pais                 =models.CharField(max_length=30, blank=True)
    provincia            =models.CharField(max_length=40, blank=True)
    ciudad               =models.CharField(max_length=40, blank=True)
    domicilio            =models.CharField(max_length=80, blank=True)
    codigo_postal        =models.CharField(max_length=50, blank=True)
    telefono             =models.CharField(max_length=30, blank=True)
    celular              =models.CharField(max_length=30, blank=True)
    documento            =models.CharField(max_length=30, blank=True)
    cuit                 =models.CharField(max_length=30, blank=True)
    #email = models.EmailField(max_length=128, blank=True, null=True, default='---@gmail.com')
    
    def __str__(self):
        return self.usuario.username

tienda/forms.py
from django.forms import ModelForm
from productos.models import Producto
from django import forms

class SearchLibroForm(forms.Form):
    querycom = forms.CharField(label='Ingresar el nombre de libro a buscar', widget=forms.TextInput(attrs={'size': 32, 'class': 'form- control'}))

class CargarForm(ModelForm):
    class Meta:
        model=Producto
        fields = ['producto', 'fecha_publicacion', 'imagen']

    def _init_(self, *args, **kwargs):
        super(CargarForm, self)._init_(*args, **kwargs)

tienda/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from productos.models import Producto
from tienda.forms import CargarForm
from django.http import Http404
from django.views.generic import View


def cargar_imagen(request):
    params={}

    if request.method == 'POST':
        form = CargarForm(request.POST, request.FILES)
        params['form']=form
        if form.is_valid():
            producto = form.cleaned_data['producto']
            fecha_publicacion = form.cleaned_data['fecha_publicacion']
            imagen = form.cleaned_data['imagen']

            nuevo_producto = Producto(producto=producto, fecha_publicacion=fecha_publicacion, imagen=imagen)
            nuevo_producto.save()
            return redirect('index')

    else:
        form = CargarForm()
        params['form'] = form
        return render(request, 'tienda/formulario.html', params)


class VerImagenes(View): 
    template = "tienda/verimagenes.html"

    def get(self, request):
        params={}
        try:
            productos = Producto.objects.all()
        except Producto.DoesNotExist:
            raise Http404
        params["productos"] = productos
        
        return render(request, self.template, params)


def ver_imagen(request, producto_id):
    params={}
    try:
        producto = Producto.objects.get(pk=producto_id)
    except Producto.DoesNotExist:
        raise Http404
    params["producto"] = producto
    
    return render(request, "tienda/verimagen.html", params)


class EjemploLocalSotage(View): 
    template = "tienda/localstorage.html"

    def get(self, request):
        params={}
        try:
            productos = Producto.objects.all()
        except Producto.DoesNotExist:
            raise Http404
        params["productos"] = productos
        # ##########################################################
        # PARA INICIALIZAR LA VARIABLE DE SESSION CARRO
        # ###########################################################
        try:
            request.session["carro"]
        except:
            request.session["carro"] = {}
            
        return render(request, self.template, params)

templates/tienda/formulario.html
{% extends "layout.html" %}
{% load static %}
{% block tienda %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 text-center py-4">
            <h1>MI TIENDA</h1>
        </div>

        <div class="col-12 col-sm-10 col-md-8 col-lg-6 bg-light p-4 rounded shadow">
            <!-- Formulario de Carga de Producto -->
            <form action="{% url 'cargar' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                
                <div class="mb-3">
                    <label for="id_producto" class="form-label">Producto:</label>
                    <input type="text" name="producto" class="form-control" maxlength="200" required id="id_producto">
                </div>

                <div class="mb-3">
                    <label for="id_fecha_publicacion" class="form-label">Fecha de publicación:</label>
                    <input type="date" name="fecha_publicacion" class="form-control" required id="id_fecha_publicacion">
                </div>

                <div class="mb-3">
                    <label for="id_imagen" class="form-label">Imagen:</label>
                    <input type="file" name="imagen" class="form-control" accept="image/*" id="id_imagen">
                </div>

                <div class="text-center">
                    <input type="submit" value="Subir producto" class="btn btn-dark mt-3">
                </div>
            </form>
        </div>

        <div class="col-12 py-5"></div>
    </div>
</div>

{% endblock %}

{% block scripts %}
    <script src="{% static 'js/jquery.js' %}"></script>    
    <script>
        $("#id_fecha_publicacion").datepicker({
            inline: true
        });
    </script>
{% endblock %}

templates/tienda/localstorage.html
{% extends "layout.html" %}
{% load static %}
{% block content %}
  <div class="container my-5">

 <!-- Botón para volver atrás -->
 <div class="mb-4">
  <button onclick="window.history.back()" class="btn btn-secondary">← Volver Atrás</button>
</div>

    <div class="row">
      {% for producto in productos %}
        <div class="col-12 col-md-4 mb-4">
          <div class="card shadow-sm">
            <a href="{% url 'ver' producto.id %}">
              <img src="/media/{{ producto.imagen }}" class="card-img-top" alt="Imagen de {{ producto.nombre }}">
            </a>
            <div class="card-body text-center">
              <input type="hidden" class="vervalor" value="1"/>
              <input type="hidden" class="verid" value="utn_{{ producto.id }}"/>
              <button type="button" class="btn btn-dark agregar">{{ producto.id }} Agregar</button>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js"></script>

<script = "text/javascript">
  /jslint browser: true/
  /jslint plusplus: true/
  /*global FormData: false */
  /global $, jQuery, alert, console/
  /*..............................................................................................
  ... PARA VALIDAR LOS DATOS .....................................................
  .............................................................................................*/
  var csrftoken = $.cookie('csrftoken');
  function csrfSafeMethod(method) {
      "use strict";
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  
  function AgregarI(cada_producto_id, valor) {
      "use strict";
  
      console.log(cada_producto_id, valor)
      $.ajax({
          beforeSend : function (xhr, settings) {
              if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                  xhr.setRequestHeader("X-CSRFToken", csrftoken);
              }
          },
          url : "/tienda/agregar/",
          type : "GET",
          data : { cada_producto_id:cada_producto_id, valor:valor},
          success : function (json) {
              console.log(json[0].idproducto.toString())
              console.log(json[0].cantida.toString())
              localStorage.setItem(json[0].idproducto.toString(), json[0].cantida.toString());
              //location.reload();
              console.log("ok++++++++++++++++++++++++")
          },
          error : function (xhr, errmsg, err) {
              console.log('Error en carga de respuesta');
          }
      });
  } 
  
  
  
  
  
  $('.agregar').click(function (event) {
      "use strict";
      event.preventDefault();
      let cada_producto_id = $(this).parent().find('.verid').val();
      let valor = $(this).parent().find('.vervalor').val();
      console.log(cada_producto_id);
      console.log(valor);
  
      //PASO 1: Remuevo todo item que no inicia con utn_
      let i;
      for(i = 0; i < localStorage.length; i++){
          let clave_eliminar = localStorage.key(i);
          console.log(typeof clave_eliminar);
          console.log(clave_eliminar);
          if(!clave_eliminar.startsWith("utn_")){
              console.log("retorna NO verdadero !!!!!!!!!!!!!");
              localStorage.removeItem(clave_eliminar);
              console.log("retorna NO verdadero !!!!!!!!!!!!!");
          }
      }
  
      //PASO 2: Si es la primera vez que selecciono el valor me quedo con "valor=1"
      //Si ya existia un valor en la base tomo ese valor en lugar de 1
      for(i = 0; i < localStorage.length; i++){
          let clave = localStorage.key(i);
          let el_valor = localStorage[clave];
          if(clave == cada_producto_id){
              console.log("-----1112------")
              console.log(clave);
              console.log(valor);
              valor = el_valor;
              console.log("-----1112------")
          }else{
              console.log("no hay coincidenciaaaa");
          }   
      }
  
      AgregarI(cada_producto_id, valor);
  
  });

  
  </script>
  {% endblock %}

templates/tienda/verimagen.html
{% extends "layout.html" %}
{% load static %}

{% block tienda %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>El ID de la imagen es: {{ producto.id }}</h1>
            
            {% if producto.imagen %}
                <img src="{{ producto.imagen.url }}" width="20%" alt="Imagen de {{ producto.nombre }}">
            {% else %}
                <p>No hay imagen disponible.</p>
            {% endif %}
            
            <a href="{% url 'ejemplo_localstorage' %}">Ir a tienda</a>
        </div>
    </div>
</div>
{% endblock %}

templates/tienda/verimagenes.html
{% extends "layout.html" %}
{% load static %}

{% block tienda %}
<div class="container">
    <div class="row">
        <div class="col-12">
            {% for producto in productos %}
                <a href="{% url 'ver' producto.id %}">
                    {% if producto.imagen %}
                        <img src="{{ producto.imagen.url }}" style="width: 30%;" alt="Imagen de {{ producto.nombre }}">
                    {% else %}
                        <img src="{% static 'img/placeholder.png' %}" style="width: 30%;" alt="Imagen no disponible">
                    {% endif %}
                </a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}