librosonline/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('vistaprevia.urls')),
   #path('accounts/', include('registration.backends.default.urls')),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('usuario/', include('usuario.urls')),  
]  +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

tienda/urls.py
from django.urls import path
from tienda import views
from tienda import views_agregar
from tienda.views import VerImagenes
from tienda.views import EjemploLocalSotage

urlpatterns = [
    path('cargar/', views.cargar_imagen, name="cargar"),
    path('<int:producto_id>/ver/', views.ver_imagen, name="ver"),  
    path('verimagenes/', VerImagenes.as_view(), name="verimagenes"),
    path('ejemplo_localstorage/', EjemploLocalSotage.as_view(), name="ejemplo_localstorage"),
    path("agregar/", views_agregar.agregar, name="agregar"),
]

vistaprevia/urls.py
from django.urls import path
from vistaprevia import views
from vistaprevia.views import Templatetags1
from vistaprevia.views import para_ajax
from vistaprevia.views import BuscarLibro
from vistaprevia.views import BuscarLibro2



urlpatterns = [
    path("", views.index, name="index"),
    path("templatetags1", Templatetags1.as_view(), name="templatetags1"),
    path("usar_ajax", views.para_ajax, name="usar_ajax"),
    path("buscar_libro/", BuscarLibro.as_view(), name="buscar_libro"),
    path("buscar_libro2/", BuscarLibro2.as_view(), name="buscar_libro2"),
    
]

vistaprevia/models.py
from django.db import models
from django.utils.html import format_html

class Categoria(models.Model):
    nombre = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)

    def _str_(self):
        return '%s' % self.nombre


class Producto(models.Model):

    Borrador = 'Borrador'
    Publicado = 'Publicado'
    Retirado = 'Retirado'
    APROBACION_PRODUCTO = (
        (Borrador, 'Borrador'),
        (Publicado, 'Publicado'),
        (Retirado, 'Retirado'),
    )
    estado = models.CharField(max_length=10, choices=APROBACION_PRODUCTO, default='Borrador')

    producto = models.CharField(max_length=200)
    fecha_publicacion = models.DateTimeField('Fecha de publicación')
    imagen = models.ImageField(upload_to="producto/%Y/%m/%d", blank=True, null=True) 
    #categoria = models.ManyToManyField(Categoria)    
    categoria = models.ForeignKey(
        Categoria, blank=False, null=True, on_delete=models.CASCADE
    )
    
    def tipo_de_producto(self):
        if self.estado == 'Retirado':
            return format_html('<span style="color: #f00;">{}</span>', self.estado, )
        elif self.estado == 'Borrador':
            return format_html('<span style="background-color: #f0f; padding:7px;">{}</span>', self.estado, )
        elif self.estado == 'Publicado':
            return format_html('<span style="color: #099;">{}</span>', self.estado, )

    def _str_(self, ):
        return self.producto + "---" + str(self.fecha_publicacion)

tienda/forms.py
from django.forms import ModelForm
from productos.models import Producto
from django import forms

class SearchLibroForm(forms.Form):
    querycom = forms.CharField(label='Ingresar el nombre de libro a buscar', widget=forms.TextInput(attrs={'size': 32, 'class': 'form- control'}))

class CargarForm(ModelForm):
    class Meta:
        model=Producto
        fields = ['producto', 'fecha_publicacion', 'imagen']

    def _init_(self, *args, **kwargs):
        super(CargarForm, self)._init_(*args, **kwargs)

vistaprevia/views.py
from datetime import datetime
from django.shortcuts import render
from django.db.models import Q
from productos.models import Producto
from django.views.generic import View
import datetime
from django.shortcuts import redirect
from tienda.forms import SearchLibroForm
import json
from django.http import HttpResponse
from django.shortcuts import HttpResponse

def para_ajax(request):
    params={}
    search=SearchLibroForm
    params['search']=search
    return render(request, 'vistaprevia/ver_ajax.html', params)

class BuscarLibro(View):

    def is_ajax(self, request):
        return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


    def get(self, request):
        if self.is_ajax(request=request):
            palabra=request.GET.get('term', '')
            print("------> 1 ", palabra)
            libro=Producto.objects.filter(producto__icontains=palabra)
            print("------> 2 ", libro)
            result=[]
            for an in libro:
                data={}
                data['label']=an.producto
                result.append(data)
            data_json=json.dumps(result)
        else:
            data_json="fallo"
        mimetype="application/json"
        return HttpResponse(data_json, mimetype)

class BuscarLibro2(View):

    def is_ajax(self, request):
        return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

    def get(self, request):
        if self.is_ajax(request=request):
            q = request.GET['valor']
            libro = Producto.objects.filter(producto__icontains=q)
            results = []
            for rec in libro:
                print(rec.producto)
                print(rec.estado)
                print(rec.imagen)

                data = {}
                data['producto'] = rec.producto
                data['estado'] = rec.estado
                data['ruta_imagen'] = str(rec.imagen)
                results.append(data)
            data_json = json.dumps(results)

        else:
            data_json = "fallo"
        mimetype = "application/json"
        return HttpResponse(data_json, mimetype)

    

def index(request):
    params = {}
    params["nombre_sitio"] = "Libros Online"
    producto = Producto.objects.filter(
        Q(estado="Publicado"),
    )
    params["producto"] = producto
    print(producto)
    return render(request, "vistaprevia/index.html", params)

class Templatetags1(View):
    template = "vistaprevia/templatetags1.html"
    def get(self, request):
        params = {}
        params["cross_site_scripting"]="""
            <script>
            $("*").css({
                "background-color": "yellow",
                "font-weight": "bolder",
            });
            </script>
        
        """
        producto = Producto.objects.filter(
            Q(estado="Publicado"),
        )
        params["los_productos"]=producto
        params["fecha_de_hoy"]=datetime.datetime.now()
        params["mi_lista"]=[1, 2, 3, 4, 5, 6, 7, 8, 9]
        params["row3"]="row3"
        params["mi_lista2"]=[]

        return render(request, self.template, params)
    def post(self, request):
        params={}
        producto=request.POST.get("producto")
        el_pedido=request.session.get("el_pedido")
        if el_pedido:
            cantidad = el_pedido.get(producto)
            if cantidad:
                el_pedido[producto]=cantidad+1
            else:
                el_pedido[producto]=1
        else:
            el_pedido={}
            el_pedido[producto]=1

        request.session["el_pedido"]=el_pedido
        print(request.session["el_pedido"])

        return redirect("templatetags1")

templates/vistaprevia/index.html
{% extends "layout.html" %}
{% load static %}
{% block contenedor %}
<header>
<!-- Hero Carousel -->
<div id="carouselExampleDark" class="carousel carousel-dark slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="3" aria-label="Slide 4"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="10000">
      <img src="{% static 'img/city5.jpg' %}" class="d-block w-100" alt="..."> 
      <div class="carousel-caption d-none d-md-block">
        <h5 class="text-white">Images created with Midjourney v.5 and v.6</h5>
        <p class="text-white">A futuristic city in Tokyo</p>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <img src="{% static 'img/city4.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5 class="text-white">Images created with Midjourney v.5 and v.6</h5>
        <p class="text-white">A futuristic city in Tokyo</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/city3.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5 class="text-white">Images created with Midjourney v.5 and v.6</h5>
        <p class="text-white">A futuristic city in Tokyo</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/city6.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5 class="text-white">Images created with Midjourney v.5 and v.6</h5>
        <p class="text-white">A futuristic city in Tokyo</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</header>

<!-- Portfolio Section -->
<a id="portfolio">
<div class="container-fluid" style="padding-left: 0px; padding-right: 0px;">
    <div class="row no-gutters">
        <div class="col-sm"><img class="img-fluid" src="{% static 'img/1.png' %}"></div>
        <div class="col-sm"><img class="img-fluid" src="{% static 'img/2.png' %}"></div>
        <div class="col-sm"><img class="img-fluid" src="{% static 'img/3.png' %}"></div>
    </div>
    <div class="row no-gutters">
        <div class="col-sm"><img class="img-fluid" src="{% static 'img/4.png' %}"></div>
        <div class="col-sm"><img class="img-fluid" src="{% static 'img/5.png' %}"></div>
        <div class="col-sm"><img class="img-fluid" src="{% static 'img/6.png' %}"></div>
    </div>
    <div class="row no-gutters">
        <div class="col-sm"><img class="img-fluid" src="{% static 'img/7.png' %}"></div>
        <div class="col-sm"><img class="img-fluid" src="{% static 'img/8.png' %}"></div>
        <div class="col-sm"><img class="img-fluid" src="{% static 'img/9.png' %}"></div>
    </div>
    <div class="row no-gutters">
        <div class="col-sm"><img class="img-fluid" src="{% static 'img/10.png' %}"></div>
        <div class="col-sm"><img class="img-fluid" src="{% static 'img/11.png' %}"></div>
        <div class="col-sm"><img class="img-fluid" src="{% static 'img/12.png' %}"></div>
    </div>
    <div class="row no-gutters">
        <div class="col-sm"><img class="img-fluid" src="{% static 'img/13.png' %}"></div>
        <div class="col-sm"><img class="img-fluid" src="{% static 'img/14.png' %}"></div>
        <div class="col-sm"><img class="img-fluid" src="{% static 'img/15.png' %}"></div>
    </div>
</div>
</a>
{% endblock %}

{% block scripts %} 
<!-- Scripts -->
<!-- Include GSAP CDN -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/gsap.min.js"></script>
<!-- Include ScrollReveal CDN -->
<script src="https://unpkg.com/scrollreveal"></script>

<script>
document.addEventListener("DOMContentLoaded", function() {
    // GSAP: Fading effect on images
    function addImageFadingEffect() {
        const images = document.querySelectorAll('.img-fluid');
        
        images.forEach(image => {
            image.addEventListener('mouseenter', () => {
                gsap.to(image, {
                    duration: 0.5,
                    opacity: 0.5,
                    ease: 'power2.out'
                });
            });

            image.addEventListener('mouseleave', () => {
                gsap.to(image, {
                    duration: 0.5,
                    opacity: 1,
                    ease: 'power2.out'
                });
            });
        });
    }
    addImageFadingEffect();

    // ScrollReveal Animations
    ScrollReveal().reveal('.carousel-caption', {
        duration: 1000,
        origin: 'bottom',
        distance: '50px',
        delay: 500,
        easing: 'ease-in-out',
        opacity: 0
    });

    ScrollReveal().reveal('.img-fluid', {
        duration: 1000,
        scale: 0.85,
        opacity: 0,
        easing: 'ease-in-out',
        interval: 150
    });
});
</script> 
{% endblock %}

templates/vistaprevia/templatetags1.html
{% extends "layout.html" %}
{% load static %}
{% load mi_tienda %}
{% block content %}

<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>

<div class="container my-5">
    <div class="row">
        <div class="col-12">
            <h1 class="text-center">Hola, estoy en templatetags</h1>
            {% autoescape on %}
            <p>{{ cross_site_scripting }}</p>
            {% endautoescape %}
        </div>
    </div>
</div>

<div class="container my-5">
    <div class="row">
        <div class="col-12">
            <h1 class="text-center">Trabajando con comentarios</h1>
            <p>Rendered text with {{ fecha_de_hoy }}</p>
        </div>
    </div>
</div>

<!-- Cycle Tag Example -->
<div class="container my-5">
    <div class="row">
        <div class="col-12">
            <h1 class="text-center">Viendo el ciclo</h1>
            <ul class="list-group">
                {% for elemento in mi_lista %}
                    <li class="list-group-item {% cycle 'row1' 'row2' 'row3' %}">
                        {{ elemento }}
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

<!-- Empty List Example -->
<div class="container my-5">
    <div class="row">
        <div class="col-12">
            <h1 class="text-center">Viendo listas vacías</h1>
            <ul class="list-group">
                {% for elemento in mi_lista2 %}
                    <li class="list-group-item {% cycle 'row1' 'row2' 'row3' %}">
                        {{ elemento }}
                    </li>
                {% empty %}
                    <li class="list-group-item {% cycle 'row1' 'row2' 'row3' %}">
                        No existen elementos
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

<!-- Filter Example -->
<div class="container my-5">
    <div class="row">
        <div class="col-12">
            <h1 class="text-center">Viendo filtros</h1>
            {% filter force_escape|lower %}
                This text will be HTML-escaped, and will appear in all lowercase.
            {% endfilter %}
        </div>
    </div>
</div>

<!-- Session Example -->
<div class="container my-5">
    <div class="row">
        <div class="col-12">
            <h1 class="text-center">Uso de Sessions</h1>
        </div>

        {% for producto in los_productos %}
            <div class="col-12 col-lg-4 mb-4">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'img/1.png' %} {{ producto.imagen }}" class="card-img-top" alt="{{ producto.producto }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ producto.producto }}</h5>
                        <p class="card-text">{{ producto.descripcion|slice:":95" }}</p>
                        {% if request.session.el_pedido %}
                            <span>{{ producto|en_pedido:request.session.el_pedido }}</span>
                        {% endif %}
                        <hr/>
                        <form action="/templatetags1" method="post">{% csrf_token %}
                            <input type="hidden" name="producto" value="{{ producto.id }}"/>
                            <input type="submit" class="btn btn-primary float-end" value="Agregar"/>
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% include "descripcion_lateral.html" with nombre="Flor" apellido="Paramidani" %}

<div class="container my-5">
    <div class="row">
        <div class="col-12">
            <br/>
        </div>
    </div>
</div>

{% endblock %}

templates/vistaprevia/ver_ajax.html
{% extends "layout.html" %}
{% load static %}

{% block contenedor %}
<div class="container">
  <div class="row">
      <div class="col-12 prueba" style="padding-top:200px;">
      </div>
  </div>
</div>

<div class="container">
  <div class="row">
      <div class="col-12 prueba">
        <section id="todos_los_productos" class="row">
            <h2 class="text-center">Seleccionar producto</h2>
            <hr/>
            <div id="contenedor_filtros" class="row">
               <div id="filtros_productos" class="col-xs-12">
                   <form id="searchr-form" action="" method="post">{% csrf_token %}
                       <div class="campo_busqueda col-xs-12">
                           {{ search }}
                           <input type="button" id="boton_prod" value="Ver datos"/>
                       </div>
                    </form>
               </div>
            </div>
            <div id="contenedor_filtrado" class="col-xs-10 col-sm-offset-2 col-sm-8  
                                              col-md-offset-4 col-md-4 "></div>
        </section>
      </div>
  </div>
</div>

<!-- BOTÓN DE VOLVER MÁS ARRIBA -->
<div class="container text-center mt-5">
    <button onclick="window.history.back()" class="btn btn-secondary btn-sm" 
            style="padding: 6px 12px !important; font-size: 14px !important;">
        ← Volver atrás
    </button>
</div>

<div class="container">
  <div class="row">
      <div class="col-12 prueba" style="padding-bottom: 250px;">
      </div>
  </div>
</div>

{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script> 
<script type="text/javascript" src="{% static 'js/ajax.js' %}"></script>
<script type="text/javascript">
  $( "#id_querycom" ).autocomplete({
       source:"/buscar_libro/"
   });
</script>
{% endblock %}